name: deploy_github_action
on:
  workflow_dispatch:

jobs:
  example-ngrok-kind-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Creating kind cluster
        uses: helm/kind-action@v1.0.0-rc.1
      - name: Install Kuboard
        run: |
          kubectl apply -f https://addons.kuboard.cn/kuboard/kuboard-v3.yaml
      - name: Expose Port for Kind
        run: |
          export ID=`docker ps | awk '{print $1}' | sed -n '2p'`
          export IP=`docker inspect ${ID} |grep IPAddress | sed -n '2p'| grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
          sudo apt-get install socat
          socat TCP4-LISTEN:30080,reuseaddr,fork TCP4:${IP}:30080 &       
      - uses: shaowenchen/debugger-action@v2
        name: debugger
        timeout-minutes: 60
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
          ngrok_addr_1: 30080
          ngrok_proto_1: http
